### Авторизация
POST http://books.local/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Список книг
GET http://books.local/books

### Просмотр книги
GET http://books.local/books/6

### Добавление книги
POST http://books.local/books
X-Api-Key: {{authCode}}
Content-Type: application/json

{
  "name": "Книга",
  "isbn": "Код2",
  "authorsIds": [1]
}

### Обновление книги
PUT http://books.local/books/11
X-Api-Key: {{authCode}}
Content-Type: application/json

{
  "name": "Книга",
  "isbn": "Код2",
  "authorsIds": [1]
}

### Список авторов
GET http://books.local/authors

### Добавление автора
POST http://books.local/authors
X-Api-Key: {{authCode}}
Content-Type: application/json

{
  "name": "Иванов Иван"
}

### Обновление автора
PUT http://books.local/authors/1
X-Api-Key: {{authCode}}
Content-Type: application/json

{
  "name": "Иванов Иван57"
}
